variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

test:general:format:
  stage: test
  image: alpine:3.7
  before_script:
    - apk update
    - apk add git
    - apk add bash
  script:
    - bash CI_KIT_PATHgithooks/check_pre_commit_CRLF.sh &
    - bash CI_KIT_PATHgithooks/check_pre_commit_jupyter.sh &
    - bash CI_KIT_PATHgithooks/check_pre_commit_new_line_at_EOF.sh &
    - bash CI_KIT_PATHgithooks/check_pre_commit_whitespace.sh &
    - wait

test:general:shellcheck:
  stage: test
  only:
    refs: ["master", "develop"]
  image: ubuntu:18.04
  before_script:
    - apt-get update
    - apt-get install shellcheck
  script:
    - bash CI_KIT_PATHgit-ci.d/run_shellcheck.sh &
    - wait
