# This is an example bitbucket-pipelines.yml script
# copied in the root dir of the repo, this will trigger the pipeline on Bitbucket

image: ubuntu:18.04

pipelines:
  default:
    - step:
        script:
          - git submodule update --init --recursive
          - bash CI_KIT_PATHgithooks/check_pre_commit_CRLF.sh &
          - bash CI_KIT_PATHgithooks/check_pre_commit_jupyter.sh &
          - bash CI_KIT_PATHgithooks/check_pre_commit_new_line_at_EOF.sh &
          - bash CI_KIT_PATHgithooks/check_pre_commit_whitespace.sh &
          - wait
    - step:
        script:
          - git submodule update --init --recursive
          - bash CI_KIT_PATHgit-ci.d/run_shellcheck.sh &
          - wait
